// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/minicloudsky/golang-in-action/ent-demo/db_instance/ent/migrate"

	"github.com/minicloudsky/golang-in-action/ent-demo/db_instance/ent/dbinstance"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DbInstance is the client for interacting with the DbInstance builders.
	DbInstance *DbInstanceClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DbInstance = NewDbInstanceClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		DbInstance: NewDbInstanceClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		DbInstance: NewDbInstanceClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DbInstance.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DbInstance.Use(hooks...)
}

// DbInstanceClient is a client for the DbInstance schema.
type DbInstanceClient struct {
	config
}

// NewDbInstanceClient returns a client for the DbInstance from the given config.
func NewDbInstanceClient(c config) *DbInstanceClient {
	return &DbInstanceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dbinstance.Hooks(f(g(h())))`.
func (c *DbInstanceClient) Use(hooks ...Hook) {
	c.hooks.DbInstance = append(c.hooks.DbInstance, hooks...)
}

// Create returns a builder for creating a DbInstance entity.
func (c *DbInstanceClient) Create() *DbInstanceCreate {
	mutation := newDbInstanceMutation(c.config, OpCreate)
	return &DbInstanceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DbInstance entities.
func (c *DbInstanceClient) CreateBulk(builders ...*DbInstanceCreate) *DbInstanceCreateBulk {
	return &DbInstanceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DbInstance.
func (c *DbInstanceClient) Update() *DbInstanceUpdate {
	mutation := newDbInstanceMutation(c.config, OpUpdate)
	return &DbInstanceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DbInstanceClient) UpdateOne(di *DbInstance) *DbInstanceUpdateOne {
	mutation := newDbInstanceMutation(c.config, OpUpdateOne, withDbInstance(di))
	return &DbInstanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DbInstanceClient) UpdateOneID(id int) *DbInstanceUpdateOne {
	mutation := newDbInstanceMutation(c.config, OpUpdateOne, withDbInstanceID(id))
	return &DbInstanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DbInstance.
func (c *DbInstanceClient) Delete() *DbInstanceDelete {
	mutation := newDbInstanceMutation(c.config, OpDelete)
	return &DbInstanceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DbInstanceClient) DeleteOne(di *DbInstance) *DbInstanceDeleteOne {
	return c.DeleteOneID(di.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DbInstanceClient) DeleteOneID(id int) *DbInstanceDeleteOne {
	builder := c.Delete().Where(dbinstance.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DbInstanceDeleteOne{builder}
}

// Query returns a query builder for DbInstance.
func (c *DbInstanceClient) Query() *DbInstanceQuery {
	return &DbInstanceQuery{
		config: c.config,
	}
}

// Get returns a DbInstance entity by its id.
func (c *DbInstanceClient) Get(ctx context.Context, id int) (*DbInstance, error) {
	return c.Query().Where(dbinstance.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DbInstanceClient) GetX(ctx context.Context, id int) *DbInstance {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DbInstanceClient) Hooks() []Hook {
	return c.hooks.DbInstance
}
