// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/minicloudsky/golang-in-action/ent-demo/db_instance/ent/dbinstance"
	"github.com/minicloudsky/golang-in-action/ent-demo/db_instance/ent/predicate"
)

// DbInstanceDelete is the builder for deleting a DbInstance entity.
type DbInstanceDelete struct {
	config
	hooks    []Hook
	mutation *DbInstanceMutation
}

// Where appends a list predicates to the DbInstanceDelete builder.
func (did *DbInstanceDelete) Where(ps ...predicate.DbInstance) *DbInstanceDelete {
	did.mutation.Where(ps...)
	return did
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (did *DbInstanceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(did.hooks) == 0 {
		affected, err = did.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DbInstanceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			did.mutation = mutation
			affected, err = did.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(did.hooks) - 1; i >= 0; i-- {
			if did.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = did.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, did.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (did *DbInstanceDelete) ExecX(ctx context.Context) int {
	n, err := did.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (did *DbInstanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: dbinstance.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dbinstance.FieldID,
			},
		},
	}
	if ps := did.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, did.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// DbInstanceDeleteOne is the builder for deleting a single DbInstance entity.
type DbInstanceDeleteOne struct {
	did *DbInstanceDelete
}

// Exec executes the deletion query.
func (dido *DbInstanceDeleteOne) Exec(ctx context.Context) error {
	n, err := dido.did.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dbinstance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dido *DbInstanceDeleteOne) ExecX(ctx context.Context) {
	dido.did.ExecX(ctx)
}
