// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/minicloudsky/golang-in-action/ent-demo/db_instance/ent/dbinstance"
	"github.com/minicloudsky/golang-in-action/ent-demo/db_instance/ent/predicate"
)

// DbInstanceQuery is the builder for querying DbInstance entities.
type DbInstanceQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DbInstance
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DbInstanceQuery builder.
func (diq *DbInstanceQuery) Where(ps ...predicate.DbInstance) *DbInstanceQuery {
	diq.predicates = append(diq.predicates, ps...)
	return diq
}

// Limit adds a limit step to the query.
func (diq *DbInstanceQuery) Limit(limit int) *DbInstanceQuery {
	diq.limit = &limit
	return diq
}

// Offset adds an offset step to the query.
func (diq *DbInstanceQuery) Offset(offset int) *DbInstanceQuery {
	diq.offset = &offset
	return diq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (diq *DbInstanceQuery) Unique(unique bool) *DbInstanceQuery {
	diq.unique = &unique
	return diq
}

// Order adds an order step to the query.
func (diq *DbInstanceQuery) Order(o ...OrderFunc) *DbInstanceQuery {
	diq.order = append(diq.order, o...)
	return diq
}

// First returns the first DbInstance entity from the query.
// Returns a *NotFoundError when no DbInstance was found.
func (diq *DbInstanceQuery) First(ctx context.Context) (*DbInstance, error) {
	nodes, err := diq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dbinstance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (diq *DbInstanceQuery) FirstX(ctx context.Context) *DbInstance {
	node, err := diq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DbInstance ID from the query.
// Returns a *NotFoundError when no DbInstance ID was found.
func (diq *DbInstanceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = diq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dbinstance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (diq *DbInstanceQuery) FirstIDX(ctx context.Context) int {
	id, err := diq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DbInstance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DbInstance entity is found.
// Returns a *NotFoundError when no DbInstance entities are found.
func (diq *DbInstanceQuery) Only(ctx context.Context) (*DbInstance, error) {
	nodes, err := diq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dbinstance.Label}
	default:
		return nil, &NotSingularError{dbinstance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (diq *DbInstanceQuery) OnlyX(ctx context.Context) *DbInstance {
	node, err := diq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DbInstance ID in the query.
// Returns a *NotSingularError when more than one DbInstance ID is found.
// Returns a *NotFoundError when no entities are found.
func (diq *DbInstanceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = diq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dbinstance.Label}
	default:
		err = &NotSingularError{dbinstance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (diq *DbInstanceQuery) OnlyIDX(ctx context.Context) int {
	id, err := diq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DbInstances.
func (diq *DbInstanceQuery) All(ctx context.Context) ([]*DbInstance, error) {
	if err := diq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return diq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (diq *DbInstanceQuery) AllX(ctx context.Context) []*DbInstance {
	nodes, err := diq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DbInstance IDs.
func (diq *DbInstanceQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := diq.Select(dbinstance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (diq *DbInstanceQuery) IDsX(ctx context.Context) []int {
	ids, err := diq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (diq *DbInstanceQuery) Count(ctx context.Context) (int, error) {
	if err := diq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return diq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (diq *DbInstanceQuery) CountX(ctx context.Context) int {
	count, err := diq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (diq *DbInstanceQuery) Exist(ctx context.Context) (bool, error) {
	if err := diq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return diq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (diq *DbInstanceQuery) ExistX(ctx context.Context) bool {
	exist, err := diq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DbInstanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (diq *DbInstanceQuery) Clone() *DbInstanceQuery {
	if diq == nil {
		return nil
	}
	return &DbInstanceQuery{
		config:     diq.config,
		limit:      diq.limit,
		offset:     diq.offset,
		order:      append([]OrderFunc{}, diq.order...),
		predicates: append([]predicate.DbInstance{}, diq.predicates...),
		// clone intermediate query.
		sql:    diq.sql.Clone(),
		path:   diq.path,
		unique: diq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DbInstance.Query().
//		GroupBy(dbinstance.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (diq *DbInstanceQuery) GroupBy(field string, fields ...string) *DbInstanceGroupBy {
	grbuild := &DbInstanceGroupBy{config: diq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return diq.sqlQuery(ctx), nil
	}
	grbuild.label = dbinstance.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.DbInstance.Query().
//		Select(dbinstance.FieldCreateTime).
//		Scan(ctx, &v)
//
func (diq *DbInstanceQuery) Select(fields ...string) *DbInstanceSelect {
	diq.fields = append(diq.fields, fields...)
	selbuild := &DbInstanceSelect{DbInstanceQuery: diq}
	selbuild.label = dbinstance.Label
	selbuild.flds, selbuild.scan = &diq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a DbInstanceSelect configured with the given aggregations.
func (diq *DbInstanceQuery) Aggregate(fns ...AggregateFunc) *DbInstanceSelect {
	return diq.Select().Aggregate(fns...)
}

func (diq *DbInstanceQuery) prepareQuery(ctx context.Context) error {
	for _, f := range diq.fields {
		if !dbinstance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if diq.path != nil {
		prev, err := diq.path(ctx)
		if err != nil {
			return err
		}
		diq.sql = prev
	}
	return nil
}

func (diq *DbInstanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DbInstance, error) {
	var (
		nodes = []*DbInstance{}
		_spec = diq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DbInstance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DbInstance{config: diq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, diq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (diq *DbInstanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := diq.querySpec()
	_spec.Node.Columns = diq.fields
	if len(diq.fields) > 0 {
		_spec.Unique = diq.unique != nil && *diq.unique
	}
	return sqlgraph.CountNodes(ctx, diq.driver, _spec)
}

func (diq *DbInstanceQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := diq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (diq *DbInstanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dbinstance.Table,
			Columns: dbinstance.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dbinstance.FieldID,
			},
		},
		From:   diq.sql,
		Unique: true,
	}
	if unique := diq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := diq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dbinstance.FieldID)
		for i := range fields {
			if fields[i] != dbinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := diq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := diq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := diq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := diq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (diq *DbInstanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(diq.driver.Dialect())
	t1 := builder.Table(dbinstance.Table)
	columns := diq.fields
	if len(columns) == 0 {
		columns = dbinstance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if diq.sql != nil {
		selector = diq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if diq.unique != nil && *diq.unique {
		selector.Distinct()
	}
	for _, p := range diq.predicates {
		p(selector)
	}
	for _, p := range diq.order {
		p(selector)
	}
	if offset := diq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := diq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DbInstanceGroupBy is the group-by builder for DbInstance entities.
type DbInstanceGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (digb *DbInstanceGroupBy) Aggregate(fns ...AggregateFunc) *DbInstanceGroupBy {
	digb.fns = append(digb.fns, fns...)
	return digb
}

// Scan applies the group-by query and scans the result into the given value.
func (digb *DbInstanceGroupBy) Scan(ctx context.Context, v any) error {
	query, err := digb.path(ctx)
	if err != nil {
		return err
	}
	digb.sql = query
	return digb.sqlScan(ctx, v)
}

func (digb *DbInstanceGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range digb.fields {
		if !dbinstance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := digb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := digb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (digb *DbInstanceGroupBy) sqlQuery() *sql.Selector {
	selector := digb.sql.Select()
	aggregation := make([]string, 0, len(digb.fns))
	for _, fn := range digb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(digb.fields)+len(digb.fns))
		for _, f := range digb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(digb.fields...)...)
}

// DbInstanceSelect is the builder for selecting fields of DbInstance entities.
type DbInstanceSelect struct {
	*DbInstanceQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dis *DbInstanceSelect) Aggregate(fns ...AggregateFunc) *DbInstanceSelect {
	dis.fns = append(dis.fns, fns...)
	return dis
}

// Scan applies the selector query and scans the result into the given value.
func (dis *DbInstanceSelect) Scan(ctx context.Context, v any) error {
	if err := dis.prepareQuery(ctx); err != nil {
		return err
	}
	dis.sql = dis.DbInstanceQuery.sqlQuery(ctx)
	return dis.sqlScan(ctx, v)
}

func (dis *DbInstanceSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(dis.fns))
	for _, fn := range dis.fns {
		aggregation = append(aggregation, fn(dis.sql))
	}
	switch n := len(*dis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		dis.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		dis.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := dis.sql.Query()
	if err := dis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
