// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/minicloudsky/golang-in-action/ent-demo/db_instance/ent/dbinstance"
	"github.com/minicloudsky/golang-in-action/ent-demo/db_instance/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dbinstanceMixin := schema.DbInstance{}.Mixin()
	dbinstanceMixinFields0 := dbinstanceMixin[0].Fields()
	_ = dbinstanceMixinFields0
	dbinstanceFields := schema.DbInstance{}.Fields()
	_ = dbinstanceFields
	// dbinstanceDescCreateTime is the schema descriptor for create_time field.
	dbinstanceDescCreateTime := dbinstanceMixinFields0[0].Descriptor()
	// dbinstance.DefaultCreateTime holds the default value on creation for the create_time field.
	dbinstance.DefaultCreateTime = dbinstanceDescCreateTime.Default.(func() time.Time)
	// dbinstanceDescUpdateTime is the schema descriptor for update_time field.
	dbinstanceDescUpdateTime := dbinstanceMixinFields0[1].Descriptor()
	// dbinstance.DefaultUpdateTime holds the default value on creation for the update_time field.
	dbinstance.DefaultUpdateTime = dbinstanceDescUpdateTime.Default.(func() time.Time)
	// dbinstance.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	dbinstance.UpdateDefaultUpdateTime = dbinstanceDescUpdateTime.UpdateDefault.(func() time.Time)
	// dbinstanceDescInstanceID is the schema descriptor for instance_id field.
	dbinstanceDescInstanceID := dbinstanceFields[0].Descriptor()
	// dbinstance.InstanceIDValidator is a validator for the "instance_id" field. It is called by the builders before save.
	dbinstance.InstanceIDValidator = dbinstanceDescInstanceID.Validators[0].(func(string) error)
	// dbinstanceDescInstanceName is the schema descriptor for instance_name field.
	dbinstanceDescInstanceName := dbinstanceFields[1].Descriptor()
	// dbinstance.DefaultInstanceName holds the default value on creation for the instance_name field.
	dbinstance.DefaultInstanceName = dbinstanceDescInstanceName.Default.(string)
	// dbinstance.InstanceNameValidator is a validator for the "instance_name" field. It is called by the builders before save.
	dbinstance.InstanceNameValidator = dbinstanceDescInstanceName.Validators[0].(func(string) error)
	// dbinstanceDescHost is the schema descriptor for host field.
	dbinstanceDescHost := dbinstanceFields[2].Descriptor()
	// dbinstance.DefaultHost holds the default value on creation for the host field.
	dbinstance.DefaultHost = dbinstanceDescHost.Default.(string)
	// dbinstance.HostValidator is a validator for the "host" field. It is called by the builders before save.
	dbinstance.HostValidator = dbinstanceDescHost.Validators[0].(func(string) error)
	// dbinstanceDescEnv is the schema descriptor for env field.
	dbinstanceDescEnv := dbinstanceFields[3].Descriptor()
	// dbinstance.EnvValidator is a validator for the "env" field. It is called by the builders before save.
	dbinstance.EnvValidator = dbinstanceDescEnv.Validators[0].(func(string) error)
	// dbinstanceDescInstanceType is the schema descriptor for instance_type field.
	dbinstanceDescInstanceType := dbinstanceFields[4].Descriptor()
	// dbinstance.DefaultInstanceType holds the default value on creation for the instance_type field.
	dbinstance.DefaultInstanceType = dbinstanceDescInstanceType.Default.(string)
	// dbinstance.InstanceTypeValidator is a validator for the "instance_type" field. It is called by the builders before save.
	dbinstance.InstanceTypeValidator = dbinstanceDescInstanceType.Validators[0].(func(string) error)
	// dbinstanceDescEngine is the schema descriptor for engine field.
	dbinstanceDescEngine := dbinstanceFields[5].Descriptor()
	// dbinstance.DefaultEngine holds the default value on creation for the engine field.
	dbinstance.DefaultEngine = dbinstanceDescEngine.Default.(string)
	// dbinstance.EngineValidator is a validator for the "engine" field. It is called by the builders before save.
	dbinstance.EngineValidator = dbinstanceDescEngine.Validators[0].(func(string) error)
	// dbinstanceDescEngineVersion is the schema descriptor for engine_version field.
	dbinstanceDescEngineVersion := dbinstanceFields[6].Descriptor()
	// dbinstance.DefaultEngineVersion holds the default value on creation for the engine_version field.
	dbinstance.DefaultEngineVersion = dbinstanceDescEngineVersion.Default.(string)
	// dbinstance.EngineVersionValidator is a validator for the "engine_version" field. It is called by the builders before save.
	dbinstance.EngineVersionValidator = dbinstanceDescEngineVersion.Validators[0].(func(string) error)
	// dbinstanceDescSpecification is the schema descriptor for specification field.
	dbinstanceDescSpecification := dbinstanceFields[7].Descriptor()
	// dbinstance.DefaultSpecification holds the default value on creation for the specification field.
	dbinstance.DefaultSpecification = dbinstanceDescSpecification.Default.(string)
	// dbinstance.SpecificationValidator is a validator for the "specification" field. It is called by the builders before save.
	dbinstance.SpecificationValidator = dbinstanceDescSpecification.Validators[0].(func(string) error)
	// dbinstanceDescInstanceStatus is the schema descriptor for instance_status field.
	dbinstanceDescInstanceStatus := dbinstanceFields[8].Descriptor()
	// dbinstance.DefaultInstanceStatus holds the default value on creation for the instance_status field.
	dbinstance.DefaultInstanceStatus = dbinstanceDescInstanceStatus.Default.(string)
	// dbinstance.InstanceStatusValidator is a validator for the "instance_status" field. It is called by the builders before save.
	dbinstance.InstanceStatusValidator = dbinstanceDescInstanceStatus.Validators[0].(func(string) error)
	// dbinstanceDescInstanceCreateTime is the schema descriptor for instance_create_time field.
	dbinstanceDescInstanceCreateTime := dbinstanceFields[9].Descriptor()
	// dbinstance.InstanceCreateTimeValidator is a validator for the "instance_create_time" field. It is called by the builders before save.
	dbinstance.InstanceCreateTimeValidator = dbinstanceDescInstanceCreateTime.Validators[0].(func(string) error)
}
