// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DbInstance is the predicate function for dbinstance builders.
type DbInstance func(*sql.Selector)
